config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :attendances
  resources :users
  resources :roles
  resources :student_courses
  resources :password_resets,  only: [:new, :create, :edit, :update]
	root 'static_page#home'
  default_url_options :host => "example.com"

  resources :courses do
    member do
      patch :student_destroy
      put :student_destroy
      delete :student_destroy
    end
  end

	get 	 '/home'	,					to: 'static_page#home'
	get 	 '/students',				to: 'users#index'
	get 	 '/courses',				to: 'courses#index'
	get 	 '/attendances',		to: 'attendances#index'
	get    '/signup',  				to: 'users#new'
  post	 '/signup',  				to: 'users#create'
  get    '/login',   				to: 'session#new'
  post   '/login',   				to: 'session#create'
  delete '/logout',  				to: 'session#destroy'
  post   '/studentname',    to: 'courses#student_name'
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	belongs_to :user
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :date, presence: true
            
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]

  # GET /attendances
  # GET /attendances.json
  def index
    if current_user.role_id == 1
      @attendances = Attendance.joins(:user)
        .select("attendances.*,users.roll_no,first_name,last_name")
        .paginate(page: params[:page], per_page: 10)
    elsif current_user.role_id == 2
      @attendances = Attendance.joins(:user)
        .select("attendances.*,users.roll_no,first_name,last_name")
        .where('user_id' => current_user.id )
        .paginate(page: params[:page], per_page: 10)
    else
      @student_id = Relation.find_by_parent_id(current_user.id)
      @attendances = Attendance.joins(:user)
        .select("attendances.*,users.roll_no,first_name,last_name")
        .where('user_id' => @student_id.student_id )
        .paginate(page: params[:page], per_page: 10)
    end
  end

  # GET /attendances/1
  # GET /attendances/1.json
  def show
    @attendance = Attendance.joins(:user)
      .select("attendances.*,users.roll_no,first_name,last_name")
      .find(params[:id])
  end

  # GET /attendances/new
  def new
    @attendance = Attendance.new
  end

  # GET /attendances/1/edit
  def edit
    @attendance = Attendance.joins(:user)
      .select("attendances.*,users.roll_no,first_name,last_name")
      .find(params[:id])
  end

  # POST /attendancesu
  # POST /attendances.json
  def create
    @attendance = Attendance.new(attendance_params)
    @user_id = User.find_by_roll_no( params[:attendance][:roll_no] )
    @attendance[:create_by] = current_user.id
    @attendance[:user_id] = @user_id.id

    respond_to do |format|
      if @attendance.save
        format.html { redirect_to @attendance}
        format.json { render :show, status: :ok, location: @attendance }
      else
        format.html { render :edit }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /attendances/1
  # PATCH/PUT /attendances/1.json
  def update
    @attendance[:start_time] = params[:start_time]
    @attendance[:end_time] = params[:end_time]
    @attendance[:date] = params[:date]
    @attendance[:remark] = params[:remark]
    @attendance[:update_by] = current_user.id
    
    respond_to do |format|
      if @attendance.update(attendance_params)
        format.html { redirect_to @attendance}
        format.json { render :show, status: :ok, location: @attendance }
      else
        format.html { render :edit }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1
  # DELETE /attendances/1.json
  def destroy
    @attendance.destroy
    redirect_to attendances_url
    flash["success"] = "Attendance was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendance_params
      params.require(:attendance).permit( :start_time,
        :end_time, :date, :remark, :user_id)
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/_form.html.erb
<div class="container">
  <%= form_with(model: attendance, local: true) do |form| %>

    <% if attendance.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>
        <ul>
        <% attendance.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :first_name, :class => "control-label col-sm-2" %>
       <div class="col-sm-10">
        <%= form.text_field :first_name, :class => "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :last_name, :class => "control-label col-sm-2" %>
       <div class="col-sm-10">
        <%= form.text_field :last_name, :class => "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :roll_no, :class => "control-label col-sm-2" %>
       <div class="col-sm-10">
        <%= form.text_field :roll_no, :class => "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :start_time, :class => "control-label col-sm-2" %>
      <div class="input-group bootstrap-timepicker timepicker col-sm-9">
        <%= form.text_field :start_time, :class => "form-control input-small", :id => "timepicker1", :value => time_format(@attendance.start_time) %>
        <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :end_time, :class => "control-label col-sm-2" %>
      <div class="input-group bootstrap-timepicker timepicker col-sm-9">
        <%= form.text_field :end_time, :class => "form-control input-small", :id => "timepicker2", :value => time_format(@attendance.end_time) %>
        <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :date, :class => "control-label col-sm-2" %>
       <div class="col-sm-10">
         <%= form.text_field :date, :class => "form-control datepicker", :value => date_dbY(@attendance.date) %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :remark, :class => "control-label col-sm-2" %>
       <div class="col-sm-10">
        <%= form.text_area :remark, :class => "form-control" %>
      </div>
    </div>

     <div class="form-group">        
      <div class="col-sm-offset-2 col-sm-2">
        <%= form.submit :class => 'btn btn-primary'%>
      </div>
    </div>

  <% end %>
</div>

<script>

  $('.datepicker').datepicker({format: 'dd-M-yyyy'});
  $('#timepicker1').timepicker();
  $('#timepicker2').timepicker();

</script>

app/views/attendances/edit.html.erb
<h1>Editing Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Show', @attendance %> |
<%= link_to 'Back', attendances_path %>

app/views/attendances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attendances</h1>

<% if can? :create, Attendance %>
  <%= link_to 'New Attendance', new_attendance_path, :class => 'btn btn-primary float-right all-btn' %>
<% end %> 

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Roll No</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Date</th>
      <th>Remark</th>
      <% if can? :create, Attendance %>
        <th colspan="3"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @attendances.each do |attendance| %>
    <% puts attendance.id %>
      <tr>
        <td><%= attendance.first_name+" "+attendance.last_name %></td>
        <td><%= attendance.roll_no %></td>
        <td><%= time_format(attendance.start_time) %></td>
        <td><%= time_format(attendance.end_time) %></td>
        <td><%= date_dbY(attendance.date) %></td>
        <td><%= attendance.remark %></td>
        <% if can? :create, Attendance %>
          <td><%= link_to 'Show', attendance, :class => 'btn 
          btn-primary all-btn' %></td>
          <td><%= link_to 'Edit', edit_attendance_path(attendance), :class =>
           'btn btn-primary all-btn' %></td>
          <td><%= link_to 'Destroy', attendance, method: :delete, data: 
          { confirm: 'Are you sure?' }, :class => 'btn btn-primary all-btn' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/attendances/new.html.erb
<h1>New Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Back', attendances_path %>

app/views/attendances/show.html.erb
<div class="container">

  <p id="notice"><%= notice %></p>

  <div class="row">
    <div  class="col-sm-3"></div>
    <div class="col-sm-3">
      <strong>Name:</strong>
    </div>
    <div class="col-sm-3">
      <%= @attendance.first_name+' '+@attendance.last_name %>
    </div>
    <div  class="col-sm-3"></div>
  </div>

  <div class="row">
    <div  class="col-sm-3"></div>
    <div class="col-sm-3">
      <strong>Roll No:</strong>
    </div>
    <div class="col-sm-3">
      <%= @attendance.roll_no %>
    </div>
    <div  class="col-sm-3"></div>
  </div>

  <div class="row">
    <div  class="col-sm-3"></div>
    <div class="col-sm-3">
      <strong>Start Time:</strong>
    </div>
    <div class="col-sm-3">
      <%= time_format(@attendance.start_time) %>
    </div>
    <div  class="col-sm-3"></div>
  </div>

  <div class="row">
    <div  class="col-sm-3"></div>
    <div class="col-sm-3">
      <strong>End time:</strong>
    </div>
    <div class="col-sm-3">
      <%= time_format(@attendance.end_time) %>
    </div>
    <div  class="col-sm-3"></div>
  </div>

  <div class="row">
    <div  class="col-sm-3"></div>
    <div class="col-sm-3">
      <strong>Date:</strong>
    </div>
    <div class="col-sm-3">
      <%= date_dbY(@attendance.date) %>
    </div>
    <div  class="col-sm-3"></div>
  </div>

  <div class="row">
    <div  class="col-sm-3 col-xs-0"></div>
    <div class="col-sm-3 col-xs-12">
      <strong>Remark:</strong>
    </div>
    <div class="col-sm-3">
      <%= @attendance.remark %>
    </div>
    <div  class="col-sm-3 col-xs-0"></div>
  </div>

  <div class="row"></div>

  <div class="row" >
    <div  class="col-md-4 col-xs-0"></div>
    <div  class="col-md-3 col-xs-12">
      <%= link_to 'Edit', edit_attendance_path(@attendance), :class => "btn btn-primary all-btn" %>
      <%= link_to 'Back', attendances_path, :class => "btn btn-primary all-btn" %>
    </div>
  </div> 

</div>