config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :attendances
  resources :users
  resources :roles
  resources :student_courses
  resources :password_resets,  only: [:new, :create, :edit, :update]
	root 'static_page#home'
  default_url_options :host => "example.com"

  resources :courses do
    member do
      patch :student_destroy
      put :student_destroy
      delete :student_destroy
    end
  end

	get 	 '/home'	,					to: 'static_page#home'
	get 	 '/students',				to: 'users#index'
	get 	 '/courses',				to: 'courses#index'
	get 	 '/attendances',		to: 'attendances#index'
	get    '/signup',  				to: 'users#new'
  post	 '/signup',  				to: 'users#create'
  get    '/login',   				to: 'session#new'
  post   '/login',   				to: 'session#create'
  delete '/logout',  				to: 'session#destroy'
  post   '/studentname',    to: 'courses#student_name'
end

app/views/layouts/_footer.html.erb
<footer class="container text-center">
  <p>
    The <%= link_to "School Management System ", root_path %>
    by Hlaing Wai Wai Htet
  </p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top bg-primary">
  <div class="container">
    <%= link_to "School Management System", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li><%= link_to "Home", root_path %></li>
          <% if can? :create, User %>
            <li><%= link_to "Student" , students_path %></li>
          <% end %>
          <li><%= link_to "Course" , courses_path %></li>
          <li><%= link_to "Attendance", attendances_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Forget Password", new_password_reset_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
       <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%#= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>